### PR TITLE
Documentation - Add detailed library usage example

### PR DESCRIPTION
**Pull request by eliihen**
This PR adds detailed usage instructions for the library, and replaces the example in `README.md` with a link to that file

See #8

### CODE REVIEW

**Comment by martijndwars** [comment]
Thanks, that's the kind of explanation I wish I had when I started with the Push API!

> Woho! First, we need to decide if we want to send a Google Cloud Messaging (GCM) message, or a Push API message. How this is done is up to you.

In practice, this distinction is made based on the endpoint of the subscription (e.g. if it starts with `https://android.googleapis.com/gcm/send`). Once this library supports [VAPID](https://datatracker.ietf.org/doc/draft-thomson-webpush-vapid/), this distinction [is no longer necessary](https://developers.google.com/web/updates/2016/07/web-push-interop-wins?hl=en) and we can handle all browser vendors in a uniform way. I plan on implementing this in the coming weeks, but just to give you a heads up :)

**Comment by eliihen** [comment]
> In practice, this distinction is made based on the endpoint of the subscription (e.g. if it starts with https://android.googleapis.com/gcm/send). 

I agree that it would be good to suggest that as an option. I'll get back to you next week with a PR updating the text!

Good to hear you are working on VAPID support! I actually wanted to make a similar guide of VAPID in the doc folder, building upon the UsageExample guide that was just merged. Once you get around to VAPID support, I'll sit down and write that as well. 

A question on VAPID: Is it possible to support all versions of Chrome that support Push simply by introducing VAPID, or will supporting earlier versions of Chrome require using the GCM constructors still? That sounds like a nightmare of if-cases, supporting different browser versions. I read the article as "If you use VAPID, all versions of chrome will support it", but not entirely sure.

**Comment by martijndwars** [comment]
It will probably be a nightmare of if-cases, but I think this nightmare is manageable (and more importantly, we can abstract all this away so that users of this library do not need to worry about this). I think l'll deprecate the `GcmNotification` object and use the endpoint to infer what kind of notification it is and whether VAPID is supported.

For example, in Chrome, non-VAPID subscriptions start with `https://android.googleapis.com/gcm/send` whereas VAPID subscriptions start with `https://android.googleapis.com/fcm`. Not sure about the other browser vendors, I need to work out some details here..

**Comment by eliihen** [comment]
> I think l'll deprecate the GcmNotification object and use the endpoint to infer what kind of notification it is and whether VAPID is supported.

Note that this will mean that you will have to keep up to date with all the browsers, when the endpoints change, when new browsers add support for Push API, and so on. If that is something you're willing to do, more power to you!

Would you be interested in opening the wiki for public editing, so that we can start mapping the VAPID and non-VAPID URLs of all the browsers in one convenient place?

**Comment by martijndwars** [comment]
Sure, I've opened the wiki for public editing! Thanks for your contributions and insights 😃

**Comment by eliihen** [comment]
No problem, it's the least I can do in return for this library! I added two pages, [Endpoints](https://github.com/MartijnDwars/web-push/wiki/Endpoints) and [A collection of URLs](https://github.com/MartijnDwars/web-push/wiki/References).

**Pull request merged**
