### PR TITLE
Update fork

### PR DESCRIPTION
**Pull request by MartijnDwars**
Hi,

I just released version 3.0.0 of the Java version. Compared to the version that was forked, this contains VAPID support and is tested with the Web Push Testing Service. It might be worth updating this fork, as it probably gets more attention than my personal repository.

Cheers,

Martijn

### CODE REVIEW

**Comment by jrconlin** [comment]
Thanks for the update!

**Comment by marco-c** [comment]
@MartijnDwars have you considered moving your repository to the web-push-libs organization?

**Comment by MartijnDwars** [comment]
I would be happy to do so. How do we arrange this?

**Comment by marco-c** [comment]
I've just invited you to the organization. You should be able to move the repo to the organization once you're a member.

**Comment by MartijnDwars** [comment]
I'm unable to transfer the repo to the organization because "The target account must not have a repository with the same name, _or a fork in the same network_." Since `web-push-libs/webpush-java` is a fork of `MartijnDwars/web-push`, they are in the same network.

Would it be possible to remove the fork? It will become redundant anyway once the transfer is complete. If you remove this repository I'll probably no longer see this issue, so I'll check back periodically.

**Pull request merged**
